### PR TITLE
Add command /groupVehicle, which lets admins give vehicles to different groups sutch as police

### PR DESCRIPTION
**Pull request by Sampuke**
Add command /groupVehicle, which lets admins give vehicles to different groups sutch as police

### CODE REVIEW

**Comment by mahanmoulaei** [comment]
@Sampuke Could you please check the update whenever you have time?

**Comment by Sampuke** [comment]
Yo, i edited some of the code you sent, it should be good, i just added an check for if the vehicle is owned then the vehicle owner is se to be no one, because vehicle cant be owned and have a group at the same time

**Comment by mahanmoulaei** [comment]
> because vehicle cant be owned and have a group at the same time

Yes it can buddy. Vehicles can be owned and also be part of a group, so not only a vehicle can belong to a group, but it can also belong to a specific player in that group...
https://github.com/esx-overextended/esx_garage/blob/b6d20ee2b725f44f6475c792970aac9557ca2e6a/server/callback.lua#L48-L51

**Comment by Sampuke** [comment]
Oh shit it can, I did not know that

**Comment by mahanmoulaei** [comment]
It’s ok. If you can revert the latest commit, that’d be appreciated

**Comment by Sampuke** [comment]
YOOO DONE

**Pull request merged**
